### ISSUE TITLE
Cookie cause bug

### ISSUE THREAD

**Issue by AndrewZuo01** [saleor/storefront#1052]
### Summary

I got Page changed from static to dynamic at runtime /default-channel/products/a-default-product, reason: cookies

### Steps to reproduce

I self deployed saleor store front and saleor platform, then I added a default product, then I clicked on the product for product detail page
```
⨯ Page changed from static to dynamic at runtime /default-channel/products/a-default-product, reason: cookies
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
    at l (/Users/andrew/Desktop/storefront/.next/server/chunks/596.js:1:3724)
    at Object.c (/Users/andrew/Desktop/storefront/.next/server/chunks/596.js:1:1447)
    at Object.getItem (/Users/andrew/Desktop/storefront/.next/server/chunks/272.js:183:4135)
    at s.getRefreshToken (/Users/andrew/Desktop/storefront/.next/server/chunks/272.js:116:5798)
    at S.fetchWithAuth (/Users/andrew/Desktop/storefront/.next/server/chunks/272.js:183:2196)
    at r (/Users/andrew/Desktop/storefront/.next/server/chunks/384.js:657:1174)
    at Module.R (/Users/andrew/Desktop/storefront/.next/server/app/[channel]/(main)/products/[slug]/page.js:6:699)
    at /Users/andrew/Desktop/storefront/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:223590
    at /Users/andrew/Desktop/storefront/node_modules/next/dist/server/lib/trace/tracer.js:131:36
    at NoopContextManager.with (/Users/andrew/Desktop/storefront/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
```
after commenting out 
<img width="472" alt="截屏2023-12-17 21 35 59" src="https://github.com/saleor/storefront/assets/59896149/0bd32e57-167a-4e3d-9863-ee0573627d72">
in src/app/[channel]/(main)/products/[slug]/page.tsx
I can access to the detail page now, but I cannot add to cart now.

## System:
 - OS: macOS 13.4
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 247.23 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 18.16.1 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.5.1 - /usr/local/bin/npm
 - pnpm: 8.12.1 - /usr/local/bin/pnpm
 - Watchman: 2022.12.26.00 - /usr/local/bin/watchman
## Browsers:
 - Chrome: 120.0.6099.109
 - Safari: 16.5
pnpm: 8.12.1

**Comment by AndrewZuo01** [comment]
This error gone roughly after I restarted laptop
